language: php

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files
    - ${TRAVIS_BUILD_DIR}/travis/module-cache

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

env:
    - TESTBENCH_VERSION=3.1.* ILLUMINATE_VERSION=5.1.* PHPUNIT_VERSION=~4.0
    - TESTBENCH_VERSION=3.2.* ILLUMINATE_VERSION=5.2.* PHPUNIT_VERSION=~4.0
    - TESTBENCH_VERSION=3.3.* ILLUMINATE_VERSION=5.3.* PHPUNIT_VERSION=~5.0
    - TESTBENCH_VERSION=3.4.* ILLUMINATE_VERSION=5.4.* PHPUNIT_VERSION=~5.7
    - TESTBENCH_VERSION=3.5.* ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0
    - TESTBENCH_VERSION=3.5.* ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0 COVERAGE=true

matrix:
    exclude:
        - php: 5.5
          env: TESTBENCH_VERSION=3.3.* ILLUMINATE_VERSION=5.3.* PHPUNIT_VERSION=~5.0
        - php: 5.5
          env: TESTBENCH_VERSION=3.4.* ILLUMINATE_VERSION=5.4.* PHPUNIT_VERSION=~5.7
        - php: 5.5
          env: TESTBENCH_VERSION=3.5.* ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0
        - php: 5.5
          env: TESTBENCH_VERSION=3.5.* ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0 COVERAGE=true
        - php: 5.6
          env: TESTBENCH_VERSION=3.5.* ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0
        - php: 5.6
          env: TESTBENCH_VERSION=3.5.* ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0 COVERAGE=true
        - php: 7.0
          env: TESTBENCH_VERSION=3.5.* ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0 COVERAGE=true

before_install: ./scripts/before_install.sh

install: ./scripts/install.sh

before_script: ./scripts/before_script.sh

script: vendor/bin/phpunit

after_success: ./scripts/after_success.sh

notifications:
    email: false
    slack:
        secure: ZilkSllOIo1vCtgUJrQ2ZQaCxW4/zpXZSFYL5Scl5o66fkgmymHR+cUqHsz9jHkXEkxOxORG1baRaJDKnyJ2A3XTfscmhOvAOupQ9jzc9M8yzugH7SrxcjDUJ02CX6LcXlOtOvPwPdkHVi9hR/qmx9D4QZEznVmvxZ2HJOVNJ18=
